image: docker:latest

cache:
  key: "ALL"
  paths:
    - target/

stages:
#  - mvnBuild
  - imageBuildDevelop
  - imageBuildMaster

#maven-build:
#  image: maven:3.5.0-jdk-8
#  stage: mvnBuild
#  script:
#    - mvn clean package -Dmaven.test.skip=true -P online
#  only:
#    - develop
#    - master

image-build-develop:
  stage: imageBuildDevelop
  script:
    - "current_date=$(TZ=England/London date +%m%d%H%M)"
    - "current_date=${current_date:0:1}$((${current_date:1:8}+800))"
    - "commit_sha=$CI_COMMIT_SHA"
    - "docker build -t $DOCKER_REGISTRY_TEST:5000/shop-service-test:$CI_COMMIT_REF_NAME-$current_date-${commit_sha:0:8} ."
    - "docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_TEST:5000"
    - "docker push $DOCKER_REGISTRY_TEST:5000/shop-service-test:$CI_COMMIT_REF_NAME-$current_date-${commit_sha:0:8}"
  only:
    - develop-no

image-build-master:
  stage: imageBuildMaster
  script:
    - "current_date=$(TZ=England/London date +%m%d%H%M)"
    - "current_date=${current_date:0:1}$((${current_date:1:8}+800))"
    - "commit_sha=$CI_COMMIT_SHA"
    - "docker build -t $DOCKER_REGISTRY_PRO:5000/shop-service-pro:$CI_COMMIT_REF_NAME-$current_date-${commit_sha:0:8} ."
    - "docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_PRO:5000"
    - "docker push $DOCKER_REGISTRY_PRO:5000/shop-service-pro:$CI_COMMIT_REF_NAME-$current_date-${commit_sha:0:8}"
  only:
    - master-no


